version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    post_create_environment:
      - pip install -e .
sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yml
