
[project]
channels = ["conda-forge"]
name = "parcels-dev"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies] # keep section in sync with pyproject.toml dependencies
python = ">=3.11"
netcdf4 = ">=1.1.9"
numpy = ">=1.9.1"
tqdm = "*"
xarray = ">=0.10.8"
uxarray = ">=2025.3.0"
dask = ">=2.0"
scikit-learn = "*"
zarr = ">=2.11.0,!=2.18.0,<3"
xgcm = ">=0.9.0"
cf_xarray = "*"
cftime = ">=1.3.1"
scipy = ">=0.16.0" #? Not sure if we rely on scipy internally anymore...
pooch = "*"

[pypi-dependencies]
parcels = { path = ".", editable = true }

[feature.tests.dependencies]
nbval = "*"
pytest = "*"
hypothesis = "*"
pytest-html = "*"
coverage = "*"

[feature.tests.tasks]
tests = "pytest"
tests-notebooks = "pytest -v -s --nbval-lax -k 'argo' docs/examples"


[feature.notebooks.dependencies]
jupyter = "*"
trajan = "*"
matplotlib-base = ">=2.0.2"

[feature.docs.dependencies]
ipython = "*" #???
numpydoc = "!=1.9.0"
nbsphinx = "*"
sphinx = "*"
pandoc = "*"
pydata-sphinx-theme = "*"
sphinx-autobuild = "*"
myst-parser = "*"
sphinxcontrib-mermaid = "*"

[feature.docs.tasks]
docs = "sphinx-build docs docs/_build"
docs-watch = 'sphinx-autobuild --ignore "*.zip" docs docs/_build'

[feature.pre-commit.dependencies]
pre_commit = "*"

[feature.pre-commit.tasks]
pre-commit = "pre-commit"

[feature.typing.dependencies]
mypy = "*"
lxml = "*" # in CI
types-tqdm = "*"

[feature.typing.tasks]
mypy = "mypy parcels"
