
[project]
channels = ["conda-forge"]
name = "parcels-dev"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
tests = "pytest"
tests-notebooks = "pytest -v -s --nbval-lax -k 'not documentation and not tutorial_periodic_boundaries and not tutorial_timevaryingdepthdimensions and not tutorial_particle_field_interaction and not tutorial_croco_3D and not tutorial_nemo_3D and not tutorial_analyticaladvection' docs/examples" # TODO v4: Mirror ci.yml for notebooks being run
coverage = "coverage run -m pytest && coverage html"
typing = "mypy parcels"
pre-commit = "pre-commit run --all-files"
docs = 'sphinx-autobuild --ignore "*.zip" docs docs/_build'

# TODO v4: Remove v4 specific tasks
tests-short = "pytest tests/test_advection.py"
tests-exclude-v4 = "pytest -m 'not v4alpha and not v4future and not v4remove'"

[dependencies] #! Keep in sync with environment.yml
python = ">=3.11"
ffmpeg = ">=3.2.3"
jupyter = "*"
matplotlib-base = ">=2.0.2"
netcdf4 = ">=1.1.9"
numpy = ">=1.9.1"
psutil = "*"
scipy = ">=0.16.0"
tqdm = "*"
xarray = ">=0.10.8"
uxarray = ">=2025.3.0"
cftime = ">=1.3.1"
dask = ">=2.0"
scikit-learn = "*"
zarr = ">=2.11.0,!=2.18.0,<3"
xgcm = ">=0.9.0"

# Notebooks
trajan = "*"

# Testing
nbval = "*"
pytest = "*"
hypothesis = "*"
pytest-html = "*"
coverage = "*"

# Typing
mypy = "*"
lxml = "*" # in CI
types-tqdm = "*"
types-psutil = "*"

# Linting
pre_commit = "*"

# Docs
ipython = "*"
numpydoc = "!=1.9.0"
nbsphinx = "*"
sphinx = "*"
pandoc = "*"
pydata-sphinx-theme = "*"
sphinx-autobuild = "*"
myst-parser = "*"
sphinxcontrib-mermaid = "*"
cf_xarray = "*"

[pypi-dependencies]
parcels = { path = ".", editable = true }
