name: Setup Conda and install parcels
description: >
  In-repo composite action to setup Conda and install parcels. Installation of parcels relies on
  `setup.py` file being available in the root. For general setup of Anaconda environments, just use
  the `conda-incubator/setup-miniconda` action (setting C variables as required).
inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml
  python-version:
    description: Python version to use.
    default: ""
runs:
  using: "composite"
  steps:
    - name: Configure pagefile # Windows compatability fix as per PR #1279
      if: ${{ runner.os == 'Windows' }}
      uses: al-cheb/configure-pagefile-action@v1.3
      with:
        minimum-size: 8GB
    - name: Install miniconda (${{ inputs.environment-file }})
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: ${{ inputs.environment-file }}
        python-version: ${{ inputs.python-version }}
        channels: conda-forge
        cache-environment: true
        cache-downloads: true
    - name: MPI support
      if: ${{ ! (runner.os == 'Windows') }}
      run: conda install -c conda-forge mpich mpi4py
      shell: bash -el {0}
    - name: Install parcels
      run: pip install .
      shell: bash -el {0}
