name: CI Additional
on:
  workflow_dispatch: # allows you to trigger manually
  schedule:
    - cron: "0 0 1 */3 *" # Run every 3 months

jobs:
  min-version-policy:
    name: Minimum Version Policy
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: min-deps
          create-args: >-
            python=3.12
            pyyaml
            conda
            python-dateutil

      - name: Core deps minimum versions policy
        run: |
          python .github/ci/min_deps_check.py .github/ci/min-core-deps.yml

  linkcheck:
    name: pixi run docs-linkcheck
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run docs-linkcheck
