name: Build and Upload to PyPI
on:
  release:
    types:
      - published
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'OceanParcels/parcels'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools setuptools-scm wheel twine check-manifest

      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          python -m build --sdist --wheel .

      - name: Check built artifacts
        run: |
          python -m twine check dist/*
          pwd
          if [ -f dist/parcels-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: releases
          path: dist

  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist

      - name: Verify the built dist/wheel is valid
        if: github.event_name == 'push'
        run: |
          python -m pip install --upgrade pip
          python -m pip install dist/parcels*.whl

      - name: Publish package to TestPyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PARCELS_PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true

  upload-to-pypi:
    needs: test-built-dist
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4

  test-pypi-release:
    needs: upload-to-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: parcels
          python-version: "3.11"
          channels: conda-forge
      - run: conda install -c conda-forge pip
      - run: pip install parcels --no-cache
      - run: curl https://raw.githubusercontent.com/OceanParcels/parcels/main/docs/examples/example_peninsula.py > example_peninsula.py
      - run: python example_peninsula.py
